import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {geoContains,geoArea} from 'd3-geo';import {COLORS,SCALES,band,rangeLabel,mergeSupplement,legendGradient,KEYS,valid,extent,normalized,color,searchCountries,toVector,fromVector,featureCode} from '../src/model.js';
const data=JSON.parse(fs.readFileSync('public/data/country_indicators.json')),geo=JSON.parse(fs.readFileSync('public/data/countries.geojson'));
test('218 country/territory entries, unique ISO, no aggregates, same-year indicators',()=>{assert.equal(data.countries.length,218);assert.equal(new Set(data.countries.map(c=>c.iso3)).size,218);assert.ok(!data.countries.some(c=>['WLD','HIC','EAS'].includes(c.iso3)));for(const c of data.countries){assert.match(c.name_zh,/[\u3400-\u9fff]/);for(const k of KEYS){assert.equal(c.metrics[k].year,2023);assert.ok(c.metrics[k].value===null||valid(c.metrics[k].value));}}});
test('coverage and missing-value exclusion',()=>{for(const [k,n] of Object.entries({population:217,population_density:215,gdp:204,gdp_per_capita:204}))assert.equal(data.countries.filter(c=>valid(c.metrics[k].value)).length,n);assert.equal(normalized(null,1,100),null);assert.equal(color(null),'#626a7b');assert.ok(KEYS.every(k=>data.countries.find(c=>c.iso3==='TWN').metrics[k].value===null));});
test('fixed ranges include their lower boundary and do not depend on global maximum',()=>{for(const k of KEYS){assert.equal(color(1,k),COLORS[0]);SCALES[k].forEach((n,i)=>{assert.equal(band(n-0.001,k),i);assert.equal(band(n,k),i+1);});assert.equal(color(1e15,k),COLORS[5]);}const rus=data.countries.find(c=>c.iso3==='RUS');assert.equal(color(rus.metrics.population.value,'population'),'#ff962f');assert.equal(rangeLabel(rus.metrics.population.value,'population'),'1億–10億');assert.equal(color(1.4e9,'population'),'#ef4444');});
test('Chinese, English and ISO search',()=>{for(const q of ['日本','Japan','JPN'])assert.ok(searchCountries(data.countries,q).some(c=>c.iso3==='JPN'));assert.ok(searchCountries(data.countries,'臺灣').some(c=>c.iso3==='TWN'));assert.equal(searchCountries(data.countries,'xyz-nothing').length,0);});
test('spherical forward/inverse coordinates and unit radius',()=>{for(const ll of [[0,0],[121,23],[-73,40],[179,-50],[-179,70]]){const v=toVector(...ll);assert.ok(Math.abs(Math.hypot(...v)-1)<1e-12);const result=fromVector({x:v[0],y:v[1],z:v[2]});assert.ok(Math.abs(ll[0]-result[0])<1e-10&&Math.abs(ll[1]-result[1])<1e-10);}});
test('Natural Earth polygon picking: countries, antimeridian and small-island alternative',()=>{for(const [id,ll] of [['JPN',[139.7,35.7]],['USA',[-100,40]],['BRA',[-50,-10]],['AUS',[134,-25]],['TWN',[121,23.7]]]){const f=geo.features.find(f=>featureCode(f)===id);assert.ok(f,id);assert.ok(geoContains(f,ll),id);assert.ok(geoArea(f)<Math.PI*2,id+' winding');}assert.ok(geo.features.every(f=>f.geometry));assert.ok(data.countries.find(c=>c.iso3==='SGP'));});

test('antimeridian, islands and ocean picking',()=>{for(const [id,ll] of [['RUS',[179,68]],['RUS',[-179,68]],['FJI',[179.95,-16.2]],['FJI',[-179.95,-16.2]],['USA',[-155.5,19.6]],['USA',[-150,65]],['FRA',[9.1,42.2]]])assert.ok(geoContains(geo.features.find(f=>featureCode(f)===id),ll),id+ll);for(const ll of [[0,0],[-140,0],[135,40]])assert.ok(!geo.features.some(f=>geoContains(f,ll)));});

test('legend shares six discrete stops and missing values are separate',()=>{assert.equal(COLORS.length,6);for(const c of COLORS)assert.ok(legendGradient().includes(c));assert.equal(color(null),'#626a7b');assert.equal(band(null,'population'),null);});
test('supplements cannot overwrite valid original WDI values or mutate source',()=>{const base=[{iso3:'AAA',metrics:{population:{value:10,year:2023},gdp:{value:null}}}];const merged=mergeSupplement(base,{countries:[{iso3:'AAA',metrics:{population:{value:99,year:2024},gdp:{value:25,year:2022,source_url:'https://en.wikipedia.org/wiki/Test'}}}]});assert.equal(merged[0].metrics.population.value,10);assert.equal(merged[0].metrics.gdp.value,25);assert.equal(merged[0].metrics.gdp.year,2022);assert.equal(merged[0].metrics.gdp.supplementary,true);assert.equal(base[0].metrics.gdp.value,null);});
test('Wikipedia additions have traceable years and preserve WDI snapshot',()=>{const supp=JSON.parse(fs.readFileSync('public/data/wikipedia_supplementary.json'));const merged=mergeSupplement(data.countries,supp);let added=0;for(const c of merged){const original=data.countries.find(x=>x.iso3===c.iso3);for(const k of KEYS){const m=c.metrics[k];if(valid(original.metrics[k].value))assert.deepEqual(m,original.metrics[k]);if(m.supplementary){added++;assert.ok(Number.isInteger(m.year));assert.match(m.source_url,/^https:\/\/en.wikipedia.org\//);assert.ok(m.note_zh);assert.ok(m.wiki_citation);}}}assert.equal(added,27);assert.equal(merged.find(c=>c.iso3==='XKX').metrics.population_density.value,null);assert.equal(merged.find(c=>c.iso3==='TWN').metrics.population.value,23829897);});
