import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM,VirtualConsole} from 'jsdom';
const html=fs.readFileSync('earth-observatory-offline.html','utf8');
async function open(){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('HTMLCanvasElement'))errors.push(e.message);});const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://example.test/globe/',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.HTMLCanvasElement.prototype.getContext=()=>null;w.structuredClone=structuredClone;}});await new Promise(r=>setTimeout(r,30));return {dom,d:dom.window.document,w:dom.window,errors};}
test('offline startup/fallback exposes full searchable data without WebGL',async()=>{const {dom,d,errors}=await open();assert.equal(d.querySelector('#loading').hidden,true);assert.equal(d.querySelector('#fallback').hidden,false);assert.ok(d.querySelectorAll('.result').length>=218);assert.equal(d.querySelectorAll('.metric').length,8);assert.match(d.querySelector('#detail').textContent,/日本/);assert.ok([...d.querySelectorAll('.controls button')].every(b=>b.disabled));assert.deepEqual(errors,[]);dom.window.close();});
test('search, select Taiwan missing data, repeated add/remove/clear and metric controls',async()=>{const {dom,d,w}=await open();const search=d.querySelector('#search');search.value='台灣';search.dispatchEvent(new w.Event('input'));d.querySelector('.result').click();assert.match(d.querySelector('#detail').textContent,/台灣/);d.querySelector('#add').click();assert.equal(d.querySelectorAll('.card').length,1);assert.equal(d.querySelector('#add').disabled,true);search.value='';search.dispatchEvent(new w.Event('input'));for(const id of ['JPN','USA','IND']){d.querySelector(`[data-code="${id}"]`).click();d.querySelector('#add').click();}assert.equal(d.querySelectorAll('.card').length,4);d.querySelector('[data-code="BRA"]').click();assert.equal(d.querySelector('#add').disabled,true);for(const key of ['gdp','gdp_per_capita','population_density','population']){d.querySelector(`[data-key="${key}"]`).click();assert.equal(d.querySelectorAll('.metric[aria-pressed="true"]').length,1);assert.ok(d.querySelector('#legend-name').textContent.length>0);assert.equal(d.querySelectorAll('.legend-bin').length,6);}d.querySelector('[data-remove="TWN"]').click();assert.equal(d.querySelectorAll('.card').length,3);for(let i=0;i<3;i++){d.querySelector('#clear').click();assert.equal(d.querySelectorAll('.card').length,0);}dom.window.close();});
test('Back restores metric, selected country and compare board',async()=>{const {dom,d,w}=await open();d.querySelector('[data-code="USA"]').click();d.querySelector('#add').click();d.querySelector('[data-key="gdp"]').click();assert.match(w.location.hash,/metric=gdp/);w.history.back();await new Promise(r=>setTimeout(r,40));assert.equal(d.querySelector('[data-key="population"]').getAttribute('aria-pressed'),'true');assert.match(d.querySelector('#detail h3').textContent,/美國/);assert.equal(d.querySelectorAll('.card').length,1);dom.window.close();});

test('Taiwan original official supplement retains a separate provenance panel',async()=>{const {dom,d}=await open();d.querySelector('[data-code="TWN"]').click();assert.match(d.querySelector('.supplement').textContent,/23,420,442/);assert.match(d.querySelector('.supplement').textContent,/不納入全球色階/);dom.window.close();});

test('Russia shows the explicit hundred-million population band',async()=>{const {dom,d}=await open();d.querySelector('[data-code="RUS"]').click();assert.match(d.querySelector('.range-badge').textContent,/第 5 級 · 1億–10億/);assert.equal(d.querySelectorAll('.legend-bin.active').length,1);assert.match(d.querySelector('.legend-bin.active').textContent,/1億–10億/);dom.window.close();});
test("all metric tabs render the shared red-ended legend",async()=>{const {legendGradient}=await import("../src/model.js");const {dom,d}=await open();const probe=d.createElement("div");probe.style.background=legendGradient();for(const key of ["population","gdp","gdp_per_capita","population_density","population"]){d.querySelector(`[data-key="${key}"]`).click();assert.equal(d.querySelector(".gradient").style.background,probe.style.background);assert.match(d.querySelector(".gradient").style.background,/239, 68, 68/);}dom.window.close();});
test('Wikipedia values show actual year/source and incompatible density stays missing',async()=>{const {dom,d}=await open();d.querySelector('[data-code="TWN"]').click();assert.match(d.querySelector('#detail').textContent,/2020/);assert.match(d.querySelector('.wiki-badge').textContent,/Wikipedia/);assert.match(d.querySelector('.source-small').textContent,/Wikipedia/);d.querySelector('#add').click();assert.match(d.querySelector('.card').textContent,/2020/);d.querySelector('[data-code="XKX"]').click();d.querySelector('[data-key="population_density"]').click();assert.equal(d.querySelector('.bigvalue').textContent,'146');assert.match(d.querySelector('.source-small').textContent,/146/);assert.match(d.querySelector('.source-small').textContent,/不納入/);dom.window.close();});

test('Taiwan density reference is visible and excluded from chart scale',async()=>{const {dom,d}=await open();d.querySelector('[data-code="TWN"]').click();d.querySelector('[data-key="population_density"]').click();assert.equal(d.querySelector('.bigvalue').textContent,'644');assert.match(d.querySelector('#detail .unit').textContent,/總面積/);assert.match(d.querySelector('#detail .unit').textContent,/密度欄未另標年/);assert.match(d.querySelector('.range-badge').textContent,/不分級/);d.querySelector('#add').click();assert.equal(d.querySelector('.card .value').textContent,'644');assert.equal(d.querySelector('.card .bar i').style.width,'0%');assert.match(d.querySelector('.card').textContent,/不計算比例/);assert.equal(d.querySelectorAll('.legend-bin.active').length,0);dom.window.close();});
