import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {geoEquirectangular,geoPath,geoContains,geoCentroid} from 'd3-geo';
import {referenceOnly,displayValue,displayUnit,displayYear,toVector,fromVector,featureCode,color,metricValue,valid,exact,METRICS,rangeLabel,provenance} from './model.js';
export function createGlobe(stage,geo,countries,onSelect){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;stage.prepend(renderer.domElement);const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','三維地球。方向鍵旋轉，加減鍵縮放；可用旁邊搜尋選國家。');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.fromArray(toVector(110,24,3.5));const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.enablePan=false;controls.minDistance=1.5;controls.maxDistance=5;controls.autoRotate=false;controls.autoRotateSpeed=.5;
 // Unlit cartographic surface preserves the legend colors at every longitude.
 renderer.toneMapping=THREE.NoToneMapping;
 const textureCanvas=document.createElement('canvas');textureCanvas.width=4096;textureCanvas.height=2048;const ctx=textureCanvas.getContext('2d');const texture=new THREE.CanvasTexture(textureCanvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const earth=new THREE.Mesh(new THREE.SphereGeometry(1,96,64),new THREE.MeshBasicMaterial({map:texture,toneMapped:false}));scene.add(earth);
 const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.045,64,48),new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 vNormal; varying vec3 vPosition; void main(){vNormal=normalize(normalMatrix*normal); vec4 p=modelViewMatrix*vec4(position,1.0);vPosition=p.xyz;gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 vNormal;varying vec3 vPosition;void main(){float rim=pow(1.0-abs(dot(normalize(vNormal),normalize(-vPosition))),3.0);gl_FragColor=vec4(0.25,0.64,0.82,rim*0.38);}'}));scene.add(atmosphere);
 const stars=new THREE.BufferGeometry(),positions=[];let seed=5321;for(let i=0;i<950;i++){seed=(seed*16807)%2147483647;const a=seed/2147483647*Math.PI*2;seed=(seed*16807)%2147483647;const z=seed/2147483647*2-1;positions.push(18*Math.sqrt(1-z*z)*Math.cos(a),18*z,18*Math.sqrt(1-z*z)*Math.sin(a));}stars.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:'#b4d2e7',size:.025,transparent:true,opacity:.65})));
 const byCode=new Map(countries.map(c=>[c.iso3,c])),projection=geoEquirectangular().scale(4096/(2*Math.PI)).translate([2048,1024]),path=geoPath(projection,ctx);let selected=null,currentKey='population';
 function paint(){ctx.fillStyle='#0b253b';ctx.fillRect(0,0,4096,2048);for(const f of geo.features){ctx.beginPath();path(f);ctx.fillStyle=color(metricValue(byCode.get(featureCode(f)),currentKey),currentKey);ctx.fill();if(!valid(metricValue(byCode.get(featureCode(f)),currentKey))){ctx.save();ctx.clip();ctx.strokeStyle='#c4ccd6';ctx.lineWidth=2;for(let x=-2048;x<4096;x+=16){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+2048,2048);ctx.stroke();}ctx.restore();}ctx.beginPath();path(f);ctx.strokeStyle='#071426';ctx.lineWidth=1.2;ctx.stroke();}if(selected){const f=geo.features.find(f=>featureCode(f)===selected.iso3);if(f){ctx.beginPath();path(f);ctx.strokeStyle='#fff4b6';ctx.lineWidth=4;ctx.stroke();}}texture.needsUpdate=true;}
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),label=document.getElementById('globe-label');let hover=null,down=null;controls.addEventListener('change',()=>{label.hidden=true;});
 function hit(e){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(earth)[0];if(!hit)return null;const ll=fromVector(hit.point);const f=geo.features.find(f=>geoContains(f,ll));return f?byCode.get(featureCode(f))??{iso3:featureCode(f),name_zh:f.properties.NAME_ZHT||f.properties.NAME_ZH||f.properties.NAME,map_only:true}:null;}
 canvas.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];label.hidden=true;});canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<6){const c=hit(e);if(c)onSelect(c.iso3,c.map_only?c:null);}down=null;});canvas.addEventListener('pointermove',e=>{if(down)return;hover=hit(e);if(hover){const rect=canvas.getBoundingClientRect();const m=hover.metrics?.[currentKey];label.textContent=hover.name_zh+' · '+exact(displayValue(m))+(referenceOnly(m)?' '+displayUnit(m,currentKey)+'\n'+provenance(m)+' 參考值 · '+displayYear(m)+'\n口徑不同，不納入色階或比例':valid(m?.value)?' '+METRICS[currentKey].unit+'\n'+rangeLabel(m.value,currentKey)+' · '+m.year+' · '+provenance(m)+(m.supplementary?'\n'+(m.note_zh||'年份與口徑可能不同，詳見資料卡。'):''):'');label.hidden=false;const half=Math.min(label.offsetWidth/2+8,rect.width/2);label.style.left=Math.max(half,Math.min(rect.width-half,e.clientX-rect.left))+'px';label.style.top=Math.max(label.offsetHeight*1.3+8,e.clientY-rect.top)+'px';canvas.style.cursor='pointer';}else{label.hidden=true;canvas.style.cursor='grab';}});canvas.addEventListener('pointerleave',()=>{label.hidden=true;});
 function zoom(f){camera.position.multiplyScalar(f);camera.position.clampLength(1.5,5);controls.update();}function reset(){camera.position.fromArray(toVector(110,24,3.5));controls.target.set(0,0,0);controls.autoRotate=false;controls.update();}
 canvas.addEventListener('keydown',e=>{const ll=fromVector(camera.position),r=camera.position.length();if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key)){e.preventDefault();controls.autoRotate=false;if(e.key==='+'||e.key==='=')zoom(.9);else if(e.key==='-')zoom(1.1);else{ll[0]+=e.key==='ArrowLeft'?-7:e.key==='ArrowRight'?7:0;ll[1]=Math.max(-80,Math.min(80,ll[1]+(e.key==='ArrowUp'?7:e.key==='ArrowDown'?-7:0)));camera.position.fromArray(toVector(...ll,r));}document.getElementById('rotate').textContent='開始自轉';document.getElementById('rotate').setAttribute('aria-pressed','false');}});
 let running=true;const resize=new ResizeObserver(()=>{const w=stage.clientWidth,h=stage.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);});resize.observe(stage);paint();function frame(){if(!running)return;requestAnimationFrame(frame);if(!document.hidden){controls.update();renderer.render(scene,camera);}}frame();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();running=false;canvas.hidden=true;document.getElementById('fallback').hidden=false;document.querySelectorAll('.controls button').forEach(b=>b.disabled=true);});
 return {setMetric(k){currentKey=k;label.hidden=true;paint();},select(c){selected=c;label.hidden=true;paint();const feature=geo.features.find(f=>featureCode(f)===c.iso3);const center=Number.isFinite(c.capital_latitude)&&Number.isFinite(c.capital_longitude)?[c.capital_longitude,c.capital_latitude]:feature?geoCentroid(feature):null;if(center){camera.position.fromArray(toVector(...center,Math.max(2.5,camera.position.length())));controls.update();}},reset,zoom,rotate(){controls.autoRotate=!controls.autoRotate;return controls.autoRotate;},dispose(){running=false;resize.disconnect();renderer.dispose();}};
}
