import './styles.css';
import taiwan from '../public/data/taiwan_supplementary.json';
import {METRICS,KEYS,metricValue,valid,extent,compact,exact,searchCountries} from './model.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dataset,countries,geo,globe=null,key='population',selected='JPN',compare=[];
function announce(t){$('#status').textContent=t;}
function renderResults(){const q=$('#search').value;const results=searchCountries(countries,q);$('#results').innerHTML=results.map(c=>`<button class="result" data-code="${c.iso3}" aria-current="${c.iso3===selected}"><span>${esc(c.name_zh)}</span><small>${esc(c.iso3)}</small></button>`).join('')||'<p>找不到相符地點。試試英文名稱或三碼國碼。</p>';}
function renderDetail(){const c=countries.find(c=>c.iso3===selected);if(!c)return;const m=c.metrics[key];$('#detail').innerHTML=`<h3>${esc(c.name_zh)}</h3><p class="en">${esc(c.name_en)} · ${esc(c.continent??'')} · ${c.iso3}</p><p class="bigvalue">${compact(m.value)}</p><span class="unit">${METRICS[key].label} · ${METRICS[key].unit} · 2023</span><div class="detail-grid">${KEYS.filter(k=>k!==key).map(k=>`<div class="datum"><small>${METRICS[k].label}</small>${compact(metricValue(c,k))}<small>${METRICS[k].unit}</small></div>`).join('')}</div><button class="add" id="add" ${compare.includes(c.iso3)||compare.length>=4?'disabled':''}>${compare.includes(c.iso3)?'已加入比較':compare.length>=4?'比較板已滿（最多 4 個）':'＋ 加入比較板'}</button><p class="source-small">精確值：${exact(m.value)} ${valid(m.value)?METRICS[key].unit:''}<br>${valid(m.value)?`來源：<a href="${esc(m.source_url)}" target="_blank" rel="noopener">World Bank WDI</a> · ${m.year}`:esc(m.note_zh||'本年度沒有可用資料，不等於零。')}</p>${c.iso3==='TWN'?`<section class="supplement"><strong>台灣補充資料</strong><p>${taiwan.metrics.population.label_zh}<br><b>${exact(taiwan.metrics.population.value)} 人</b></p><p>${esc(taiwan.notice_zh)}</p><a href="${taiwan.metrics.population.source_url}" target="_blank" rel="noopener">內政部戶政司 · 2024-01-10發布</a></section>`:''}`;$('#add').onclick=()=>{if(compare.length<4&&!compare.includes(selected))compare.push(selected);renderDetail();renderCompare();saveHash();announce('已加入比較板');};}
function renderCompare(){const cs=compare.map(id=>countries.find(c=>c.iso3===id)).filter(Boolean),max=Math.max(0,...cs.map(c=>metricValue(c,key)||0));$('#compare-count').textContent=`${cs.length} / 4`;$('#cards').innerHTML=cs.length?cs.map(c=>{const v=metricValue(c,key);return `<article class="card"><button class="remove" aria-label="移除${esc(c.name_zh)}" data-remove="${c.iso3}">×</button><h3>${esc(c.name_zh)}</h3><div class="value">${compact(v)}</div><span class="unit">${METRICS[key].unit} · 2023</span><div class="bar"><i style="width:${valid(v)&&max?v/max*100:0}%"></i></div><p>${valid(v)?`精確值：${exact(v)}`:'本年度無資料；不計算比例。'}</p></article>`;}).join(''):'<div class="empty">從右方搜尋選擇地點，再按「加入比較板」。</div>';$('#compare-note').textContent=`最多 4 個國家與地區 · 目前比較${METRICS[key].label}。比較板長條為線性比例，以已選最大值為 100%（與地球的對數色階不同）。`;}
function renderMetric(){document.querySelectorAll('.metric').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.key===key)));const [min,max]=extent(countries,key);$('#legend-name').textContent=`${METRICS[key].label} · ${METRICS[key].unit} · 2023`;$('#ticks').innerHTML=[0,.25,.5,.75,1].map(t=>`<span>${compact(Math.pow(10,Math.log10(min)+(Math.log10(max)-Math.log10(min))*t))}</span>`).join('');$('#coverage').textContent=`有資料 ${countries.filter(c=>valid(metricValue(c,key))).length} / ${countries.length}`;$('#lesson-title').textContent=METRICS[key].short;$('#lesson').textContent=METRICS[key].hint;renderDetail();renderCompare();globe?.setMetric(key);}
function choose(id,push=true){if(!countries.some(c=>c.iso3===id))return;selected=id;renderResults();renderDetail();globe?.select(countries.find(c=>c.iso3===id));if(push)saveHash();announce(`已選擇${countries.find(c=>c.iso3===id).name_zh}`);}
function saveHash(){const p=new URLSearchParams({metric:key,country:selected});if(compare.length)p.set('compare',compare.join(','));history.pushState(null,'','#'+p);}
function readHash(){const p=new URLSearchParams(location.hash.slice(1));key=KEYS.includes(p.get('metric'))?p.get('metric'):'population';selected=countries.some(c=>c.iso3===p.get('country'))?p.get('country'):'JPN';compare=[...new Set((p.get('compare')||'').split(','))].filter(id=>countries.some(c=>c.iso3===id)).slice(0,4);renderMetric();choose(selected,false);}
async function init(){try{[dataset,geo]=await Promise.all(['country_indicators.json','countries.geojson'].map(async f=>{const r=await fetch(`${import.meta.env.BASE_URL}data/${f}`);if(!r.ok)throw Error('資料載入失敗');return r.json();}));countries=dataset.countries;$('.metrics').innerHTML=KEYS.map(k=>`<button class="metric" data-key="${k}" aria-pressed="false">${METRICS[k].label}<span>${METRICS[k].short}</span></button>`).join('');$('.metrics').onclick=e=>{const b=e.target.closest('[data-key]');if(b){key=b.dataset.key;renderMetric();saveHash();}};$('#search').oninput=renderResults;$('#results').onclick=e=>{const b=e.target.closest('[data-code]');if(b)choose(b.dataset.code);};$('#clear').onclick=()=>{compare=[];renderCompare();renderDetail();saveHash();};$('#cards').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){compare=compare.filter(id=>id!==b.dataset.remove);renderCompare();renderDetail();saveHash();}};$('#source-content').innerHTML=`<p>${esc(dataset.metadata.year_choice_zh)} ${esc(dataset.metadata.missing_policy_zh)}</p><p>人口密度使用陸地面積。GDP 為現價美元，不是購買力平價（PPP），會受匯率與物價影響。各統計口徑可能不同；不應用這些數字判斷人民價值。</p><p>統計來源：The World Bank, World Development Indicators。此站為排除區域與收入群組的 2023 年選集；另加台灣缺值條目。下載日 ${esc(dataset.metadata.retrieved_at)}。</p><ul>${KEYS.map(k=>`<li><a target="_blank" rel="noopener" href="${esc(dataset.indicators[k].source_url)}">${METRICS[k].label}</a></li>`).join('')}</ul><p><a href="https://data.worldbank.org/summary-terms-of-use" target="_blank" rel="noopener">World Bank 資料授權：CC BY 4.0 與附加條款</a> · 中文名稱使用 <a href="https://www.unicode.org/license.txt" target="_blank" rel="noopener">Unicode CLDR（Unicode License v3）</a>。本作品不代表來源機構背書。</p><p>${esc(dataset.metadata.geography_disclaimer_zh)} 搜尋定位使用首府位置，不是國土幾何中心。台灣未混入不同年份或未核對資料，四項顯示無資料。</p>`;readHash();window.addEventListener('popstate',readHash);
 try{const probe=document.createElement('canvas');if(!probe.getContext('webgl2'))throw Error('WebGL 2 unavailable');const {createGlobe}=await import('./globe.js');globe=createGlobe($('#stage'),geo,countries,(id,mapOnly)=>{if(mapOnly){$('#detail').innerHTML=`<h3>${esc(mapOnly.name_zh)}</h3><p class="source-small">這個地圖區域不在本次 WDI 國家與地區資料清單中，因此沒有可比較數值。此處地圖標籤沿用 Natural Earth；不代表主權判斷。請搜尋其他國家與地區。</p>`;announce(mapOnly.name_zh+'：無可比較資料');}else choose(id);});globe.setMetric(key);globe.select(countries.find(c=>c.iso3===selected));$('#rotate').onclick=()=>{const active=globe.rotate();$('#rotate').textContent=active?'暫停自轉':'開始自轉';$('#rotate').setAttribute('aria-pressed',active);};$('#zoom-in').onclick=()=>globe.zoom(.85);$('#zoom-out').onclick=()=>globe.zoom(1.15);$('#reset').onclick=()=>{globe.reset();$('#rotate').textContent='開始自轉';$('#rotate').setAttribute('aria-pressed','false');};}catch(err){$('#fallback').hidden=false;document.querySelectorAll('.controls button').forEach(b=>b.disabled=true);console.warn('3D unavailable; data interface remains active.',err.message);}$('#loading').hidden=true;
 }catch(err){$('#loading').textContent='資料無法載入。請透過本機伺服器開啟網站，或重新整理重試。';console.error(err);}}
init();
