import {METRICS,valid,exact,provenance} from './model.js';
const PAIRS=[
 ['aging','JPN','IND','人口多，不代表高齡人口占比高。這題比較的是百分比，不是長者總人數。'],
 ['life_expectancy','USA','JPN','預期壽命依當年的死亡率計算，不是每一個人都會活到這個歲數。要解釋差距，還需要醫療、生活條件等資料。'],
 ['secondary_completion','NGA','USA','這是UNESCO初中完成率模型估計，不是入學率或考試分數；反映教育機會的一個面向，不能用來評價學生能力。'],
 ['co2_per_capita','IND','USA','比較的是每人平均，不是全國排放總量。生產端數字也不能直接當作一位居民的消費碳足跡。'],
 ['aging','BRA','FRA','高齡人口占比和人口總量是不同問題。年齡結構沒有單一的好壞分數。'],
 ['life_expectancy','NGA','BRA','這是2023年出生時預期壽命。平均值不表示每個地區、性別或家庭都有相同條件。'],
 ['secondary_completion','FRA','VNM','兩國採同一年、同一模型指標。估計存在不確定性，不能把微小差距當作確定排名；這裡也沒有測量學習品質。'],
 ['co2_per_capita','DEU','BRA','本題只計CO₂，排除土地利用與林業，並非全部溫室氣體。比較時要先確認範圍，不能只看數字。']
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function quizQuestions(countries){const byId=new Map(countries.map(c=>[c.iso3,c]));return PAIRS.flatMap(([key,a,b,explanation])=>{const left=byId.get(a),right=byId.get(b),ma=left?.metrics[key],mb=right?.metrics[key];if(!ma?.quiz_eligible||!mb?.quiz_eligible||!valid(ma.value)||!valid(mb.value)||ma.year!==mb.year||ma.comparison_group!==mb.comparison_group||Math.abs(ma.value-mb.value)<.1)return [];return [{id:key+'-'+a+'-'+b,key,left,right,year:ma.year,answer:ma.value>mb.value?a:b,explanation}];});}
export function initialQuiz(){return {index:0,guess:null,revealed:false};}
export function quizTransition(state,action,questions){const q=questions[state.index];if(action.type==='reset')return initialQuiz();if(!q)return state;if(action.type==='guess'&&!state.revealed&&[q.left.iso3,q.right.iso3].includes(action.code))return {...state,guess:action.code};if(action.type==='reveal'&&state.guess)return {...state,revealed:true};if(action.type==='next'&&state.revealed)return {index:(state.index+1)%questions.length,guess:null,revealed:false};return state;}
export function mountQuiz(root,countries){const questions=quizQuestions(countries);let state=initialQuiz();function render(){const q=questions[state.index];if(!q){root.innerHTML='<h2>先猜再揭曉</h2><p>目前沒有符合相同年份與口徑的題目。</p>';return;}const m=METRICS[q.key];root.innerHTML=`<div class="section-head"><div><p class="eyebrow">讓直覺遇見資料</p><h2>先猜，再揭曉。</h2></div><button data-quiz="reset">重新開始</button></div><p class="quiz-progress">第 ${state.index+1} / ${questions.length} 題 · ${q.year} · ${m.label}${q.key==='secondary_completion'?'（模型估計）':''}</p><h3 class="quiz-question">哪一個地方的${m.label}${q.key==='secondary_completion'?'模型估計值':''}較高？</h3><p class="quiz-definition">${esc(m.hint)}</p><div class="quiz-options">${[q.left,q.right].map((c,i)=>`<button data-guess="${c.iso3}" aria-pressed="${state.guess===c.iso3}" ${state.revealed?'disabled':''}><small>${i?'B':'A'}</small>${esc(c.name_zh)}${state.revealed?`<strong>${exact(c.metrics[q.key].value)} ${m.unit}</strong>`:''}</button>`).join('')}</div><div class="quiz-actions"><button class="quiz-reveal" data-quiz="reveal" ${!state.guess||state.revealed?'disabled':''}>揭曉答案</button><button data-quiz="next" ${state.revealed?'':'disabled'}>${state.index===questions.length-1?'再玩一輪':'下一題 →'}</button><span>${state.guess&&!state.revealed?'已選好，可以揭曉了。':'先選一個地方，再看數字。'}</span></div><div class="quiz-answer" aria-live="polite">${state.revealed?`<h3>${state.guess===q.answer?'猜中了！':'這次答案是另一個地方。'} ${esc(countries.find(c=>c.iso3===q.answer).name_zh)}的數值較高。</h3><p>${esc(q.explanation)}</p><p class="source-small">${[q.left,q.right].map(c=>`${esc(c.name_zh)}：<a href="${esc(c.metrics[q.key].source_url)}" target="_blank" rel="noopener">${esc(provenance(c.metrics[q.key]))}</a> · ${q.year}`).join('<br>')}</p>`:''}</div>`;}
root.addEventListener('click',e=>{const guess=e.target.closest('[data-guess]'),action=e.target.closest('[data-quiz]');if(!guess&&!action)return;const type=guess?'guess':action.dataset.quiz;state=quizTransition(state,{type,code:guess?.dataset.guess},questions);render();if(type==='reveal'){const status=root.ownerDocument.getElementById('status');if(status)status.textContent=root.querySelector('.quiz-answer').textContent;}if(type==='next'||type==='reset')root.querySelector('[data-guess]')?.focus();else if(type==='guess')root.querySelector(`[data-guess="${state.guess}"]`)?.focus();else if(type==='reveal')root.querySelector('[data-quiz="next"]')?.focus();});render();}
